### ISSUE TITLE
Saves +LAN (DM+CS1.6?)

### ISSUE THREAD

**Issue by DarthTater69** [x8BitRain/webXash#4]
Saves don't seem to save. Is this a bug or an omission? I also can't get LAN to work for Deathmatch nor could I get Counter-Strike working correctly. 

Running my own zip file of my Half-Life directory w/ the expansions via chrome.

**Comment by x8BitRain** [comment]
You have to zip the valve folder (steamapps/Half-Life/valve), not the entire HL directory to get the ZIP loading, will add to readme. As for CS it requires a custom xash build to get working from what I can tell. I'll probably remove HLDM because there is no multiplayer ability because it requires a proxy server to work as per: https://github.com/FWGS/xash3d/blob/0.19.x/README.emscripten.md#network-proxy

I'll see if I can get saves working because there is a way to save them into indexedDB but i haven't enabled that.

**Comment by DarthTater69** [comment]
Would I be able to port that custom xash build to emscription myself? And if so would it be capable of multiplayer via a proxy?

**Comment by x8BitRain** [comment]
Yes you can, you can see an example of how to initialize it with a specific proxy socket here https://github.com/iCrazyBlaze/Xash3D-Emscripten/blob/master/xash.html#L499
